version: "3.9"
services:
  db:
    image: postgres
    container_name: db-branas
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: app
    volumes:
      - ./db/data:/var/lib/postgresql/data